config/routes.rb
Delwin::Application.routes.draw do
	resources :articles, :categories, :books

	root to: 'articles#index'
		
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :excerpt, :main_image, :slug, :title, :category_ids
  has_and_belongs_to_many :categories
  
  before_create :create_slug
  
  mount_uploader :main_image, ImageUploader
  
  def to_param
  	slug
  end
  
  def create_slug
  	self.slug = self.title.parameterize
  end
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :cover_image, :date_finished, :date_started, :description, :link, :summary, :title
  
  mount_uploader :cover_image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :slug
  has_and_belongs_to_many :article
  
  before_create :create_slug
  
  def to_param
  	slug
  end
  
  def create_slug
  	self.slug = self.name.parameterize
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :author, :comment, :email, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
		@categories = Category.find(:all, :order => 'name ASC')
	end
	
	def create
  	@article = Article.new(params[:article])
    
  	if @article.save
  		flash[:success] = 'Article posted'
  		redirect_to root_path
  	else
  		render "new"
  	end
  end
	
	def show
		@article = Article.find_by_slug(params[:id])
	end
	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	
	def index
		@books = Book.all
	end
	
	def new
		@book = Book.new
	end
	
	def create
		@book = Book.new(params[:book])
		
		if @book.save
			flash[:success] = 'Book added'
			redirect_to books_path
		else
			render "new"
		end
	end
	
	def show
		@book = Book.find_by_id(params[:id])
	end
	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end
	
	def create
		@category = Category.new(params[:category])
		
		if @category.save
  		flash[:success] = 'Category added'
  		redirect_to root_path
  	else
  		render "new"
  	end
  end
  
  def show
  	@category = Category.find_by_slug(params[:id])
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_error_messages.html.haml
- if @article.errors.any?
	
	#error_explanation
		.alert.alert-error
			The form contains
			= pluralize @article.errors.count, "error"
		%ul
			- @article.errors.full_messages.each do |msg|
				%li= msg

app/views/articles/_fields.html.haml
= render 'error_messages'

= f.label :title 
= f.text_field :title 

= f.label :slug 
= f.text_field :slug 
 
= f.label :main_image
= f.file_field :main_image

= f.label :body 
= f.text_area :body, :rows => 5

= f.label 'Category'
= collection_select :article, :category_ids, @categories, :id, :name, { :selected => @article.category_ids }, { :multiple => true, :name => 'article[category_ids][]' }

= f.label :excerpt
= f.text_area :excerpt, :rows => 5

app/views/articles/index.html.haml
%h2
	All the posts
= link_to 'Add new post', new_article_path
	
- @articles.each do |article|
	%section.article
		%h1= link_to article.title, article_path(article)
		= image_tag article.main_image.to_s
		%section.content= article.body
		.categories 
			%strong Categories: 
			- article.categories.each do |c|
				= c.name
			
		
	

app/views/articles/new.html.haml
- provide :title, 'New article'

%h1 New article

.row
	.span9
		= form_for @article do |f|
			= render 'fields', f: f
			.submit= f.submit 'Post article', class: 'btn btn-large btn-primary'

app/views/articles/show.html.haml
%section.article
	%h1= @article.title
	= image_tag @article.main_image.to_s
	%section.content= @article.body
	= link_to "Edit this article", edit_article_path

app/views/books/_fields.html.haml
=# render 'error_messages'

= f.label :title 
= f.text_field :title 

= f.label :author 
= f.text_field :author 

= f.label :link 
= f.text_field :link
 
= f.label :cover_image
= f.file_field :cover_image

= f.label 'Started reading'
= f.date_select :date_started

= f.label 'Finished reading'
= f.date_select :date_finished

= f.label :summary 
= f.text_area :summary, :rows => 8

= f.label :description
= f.text_area :description, :rows => 8

app/views/books/index.html.haml
- provide :title, 'Books'

%h2 Books I've read
%p= link_to 'Add a book', new_book_path
%section.book-list
	- @books.each do |b|
		%h1= link_to b.title, book_path(b)
		%p
			Some hotshot named
			= b.author
			wrote this.
		%p= b.summary
		

app/views/books/new.html.haml
- provide :title, 'New book review'

%h1 New book review

.row
	.span9
		= form_for @book do |f|
			= render 'fields', f: f
			.submit= f.submit 'Post book review', class: 'btn btn-large btn-primary'

app/views/books/show.html.haml
- provide :title, 'Yes, I *have* read ' + @book.title

%h1= @book.title
%p= 'By ' + @book.author
= image_tag @book.cover_image.to_s
%p= link_to 'Buy this book', @book.link

%p
	%strong Here's what it's about:
%p= @book.summary

%p 
	%strong And here's what I thought:
%p= @book.description

app/views/categories/_fields.html.haml
= f.label :name
= f.text_field :name

= f.label :slug
= f.text_field :slug

= f.label :description
= f.text_area :description

app/views/categories/index.html.haml
- provide :title, 'Browse by category'

%h2 Browse by category

%p Here is a list of all the categories.

%ul.category-list
	- @categories.each do |c|
		= link_to c.name, category_path(c)

app/views/categories/new.html.haml
- provide :title, 'New category'

%h1 New category

.row
	.span9
		= form_for @category do |f|
			= render 'fields', f: f
			.submit= f.submit 'Add category', class: 'btn btn-large btn-primary'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Delwin", root_path, :class => 'brand'

%ul.nav
	%li= link_to "Writing", articles_path
	%li= link_to "Categories", categories_path
	%li= link_to "Books", books_path
	
	

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Delwin"
      %meta{:content => content_for?(:description) ? yield(:description) : "Delwin", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main